//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tattoo.InkVibesTattoo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceEs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceEs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tattoo.InkVibesTattoo.Resources.ResourceEs", typeof(ResourceEs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acepto recibir mensajes promocionales enviados a través de un marcador automático.
        /// </summary>
        public static string AcceptConditions {
            get {
                return ResourceManager.GetString("AcceptConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIRECCIÓN.
        /// </summary>
        public static string AddressLabel {
            get {
                return ResourceManager.GetString("AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somos un equipo apasionado y talentoso, dedicado a las artes visuales y a la creación de experiencias únicas para nuestros clientes. Con una sólida formación en diferentes disciplinas artísticas, combinamos creatividad, técnica y un enfoque personalizado para transformar cada idea en una obra de arte. Desde los primeros bocetos hasta la ejecución final, trabajamos en estrecha colaboración con nuestros clientes para asegurarnos de que cada proyecto refleje su individualidad y estilo. Nuestro compromiso es en [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AdrianBio {
            get {
                return ResourceManager.GetString("AdrianBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANDYSOFT Studio.
        /// </summary>
        public static string AdrianName {
            get {
                return ResourceManager.GetString("AdrianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estudio.
        /// </summary>
        public static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blanco y Negro.
        /// </summary>
        public static string BlackAndWhite {
            get {
                return ResourceManager.GetString("BlackAndWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESERVA YA!.
        /// </summary>
        public static string BookNow {
            get {
                return ResourceManager.GetString("BookNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESERVA YA!.
        /// </summary>
        public static string BookNowButton {
            get {
                return ResourceManager.GetString("BookNowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En nuestro estudio fotográfico, la atención al detalle es nuestra principal prioridad. Nos esforzamos meticulosamente por crear un entorno limpio, organizado y acogedor para nuestros clientes. Su comodidad y satisfacción son fundamentales para nosotros, y nuestro compromiso con un estudio profesional y en perfecto estado refleja nuestra dedicación a ofrecer la mejor experiencia fotográfica posible..
        /// </summary>
        public static string CommitmentDescription {
            get {
                return ResourceManager.GetString("CommitmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestro Compromiso con la Calidad.
        /// </summary>
        public static string CommitmentTitle {
            get {
                return ResourceManager.GetString("CommitmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completado.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contáctenos.
        /// </summary>
        public static string ContactUsTitle {
            get {
                return ResourceManager.GetString("ContactUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string CookieConsent_Accept {
            get {
                return ResourceManager.GetString("CookieConsent_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este sitio web utiliza almacenamiento local para asegurar que obtengas la mejor experiencia..
        /// </summary>
        public static string CookieConsent_Message {
            get {
                return ResourceManager.GetString("CookieConsent_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estilos Diversos.
        /// </summary>
        public static string DiverseStyles {
            get {
                return ResourceManager.GetString("DiverseStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha final debe ser mayor que la inicial.
        /// </summary>
        public static string EndDateInvalid {
            get {
                return ResourceManager.GetString("EndDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preguntas Frecuentes.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preguntas Frecuentes.
        /// </summary>
        public static string FAQTitle {
            get {
                return ResourceManager.GetString("FAQTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encuéntranos.
        /// </summary>
        public static string FindUsButton {
            get {
                return ResourceManager.GetString("FindUsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destacados.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta.
        /// </summary>
        public static string GetDirections {
            get {
                return ResourceManager.GetString("GetDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preguntas Frecuentes.
        /// </summary>
        public static string HeaderFAQ {
            get {
                return ResourceManager.GetString("HeaderFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Vamos a EMPEZAR!.
        /// </summary>
        public static string InitViewButton {
            get {
                return ResourceManager.GetString("InitViewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu historia en cada imagen, arte en cada detalle..
        /// </summary>
        public static string InitViewTitle {
            get {
                return ResourceManager.GetString("InitViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inválido.
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha no válida.
        /// </summary>
        public static string InvalidDates {
            get {
                return ResourceManager.GetString("InvalidDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Es una cobertura?.
        /// </summary>
        public static string IsCoverUp {
            get {
                return ResourceManager.GetString("IsCoverUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprender Más.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puede subir un máximo de .
        /// </summary>
        public static string MaximunFiles {
            get {
                return ResourceManager.GetString("MaximunFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destacados.
        /// </summary>
        public static string MyWorkTitle {
            get {
                return ResourceManager.GetString("MyWorkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Límite.
        /// </summary>
        public static string OnLimit {
            get {
                return ResourceManager.GetString("OnLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunes - Domingo: 10am - 7pm.
        /// </summary>
        public static string OpeningHours {
            get {
                return ResourceManager.GetString("OpeningHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HORARIO DE APERTURA.
        /// </summary>
        public static string OpeningHoursLabel {
            get {
                return ResourceManager.GetString("OpeningHoursLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación satisfactoria.
        /// </summary>
        public static string OperationSuccess {
            get {
                return ResourceManager.GetString("OperationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizamos sistemas de iluminación de última generación que garantizan la perfecta captación de cada detalle, adaptándonos a las necesidades específicas de cada sesión..
        /// </summary>
        public static string OurInkDescription {
            get {
                return ResourceManager.GetString("OurInkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestra Iluminación.
        /// </summary>
        public static string OurInkTitle {
            get {
                return ResourceManager.GetString("OurInkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguimos un riguroso proceso de edición y postproducción para que cada fotografía refleje la visión y estilo único de nuestros clientes, asegurando un acabado profesional en cada proyecto..
        /// </summary>
        public static string OurNeedlesDescription {
            get {
                return ResourceManager.GetString("OurNeedlesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestro Proceso.
        /// </summary>
        public static string OurNeedlesTitle {
            get {
                return ResourceManager.GetString("OurNeedlesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas las cámaras y equipos utilizados en Candysoft Studio cumplen con los más altos estándares de la industria, asegurando la máxima calidad en cada imagen..
        /// </summary>
        public static string OurProcessDescription {
            get {
                return ResourceManager.GetString("OurProcessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestro Equipo.
        /// </summary>
        public static string OurProcessTitle {
            get {
                return ResourceManager.GetString("OurProcessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo el equipo y las áreas de trabajo en Candysoft Studio se mantienen impecablemente organizados y esterilizados para ofrecer un entorno seguro y cómodo para nuestros clientes..
        /// </summary>
        public static string OurSafetyDescription {
            get {
                return ResourceManager.GetString("OurSafetyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestra Seguridad.
        /// </summary>
        public static string OurSafetyTitle {
            get {
                return ResourceManager.GetString("OurSafetyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tengo más de 18 años.
        /// </summary>
        public static string OverAge {
            get {
                return ResourceManager.GetString("OverAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al continuar, aceptas nuestra política de cookies..
        /// </summary>
        public static string PolicyNote {
            get {
                return ResourceManager.GetString("PolicyNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string PreferredDate {
            get {
                return ResourceManager.GetString("PreferredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora.
        /// </summary>
        public static string PreferredTime {
            get {
                return ResourceManager.GetString("PreferredTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudflare puede recopilar información sobre las solicitudes que se hacen a nuestro sitio web, incluyendo direcciones IP, encabezados HTTP y datos de rendimiento. Esta información se utiliza para mejorar el rendimiento y la seguridad del servicio. Cloudflare no almacena datos personales con fines de seguimiento o marketing..
        /// </summary>
        public static string PrivacyPolicy_Cloudflare_Data_Description {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Cloudflare_Data_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Qué datos recopila Cloudflare?.
        /// </summary>
        public static string PrivacyPolicy_Cloudflare_Data_Title {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Cloudflare_Data_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizamos Cloudflare CDN (Content Delivery Network) para mejorar el rendimiento y la seguridad de nuestro sitio web. Cloudflare almacena en caché una copia de nuestro sitio en múltiples ubicaciones alrededor del mundo, lo que permite que los usuarios accedan al contenido más rápidamente desde el servidor más cercano a ellos. Además, Cloudflare ofrece protección contra ataques DDoS y otras amenazas de seguridad..
        /// </summary>
        public static string PrivacyPolicy_Cloudflare_Description {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Cloudflare_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uso de CDN Cloudflare.
        /// </summary>
        public static string PrivacyPolicy_Cloudflare_Title {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Cloudflare_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PrivacyPolicy_Contact {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta política de privacidad explica qué datos recopilamos y cómo los utilizamos. Debes leer esta política para entender qué tipo de datos almacenamos en tu dispositivo y cómo se usa esa información..
        /// </summary>
        public static string PrivacyPolicy_Description {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puedes deshabilitar el almacenamiento local ajustando la configuración en tu navegador (consulta la Ayuda de tu navegador para saber cómo hacerlo). Ten en cuenta que deshabilitar el almacenamiento local afectará la funcionalidad de este y muchos otros sitios web que visitas. Deshabilitar el almacenamiento local generalmente resultará en también deshabilitar ciertas funcionalidades y características de este sitio. Por lo tanto, se recomienda que no deshabilites el almacenamiento local..
        /// </summary>
        public static string PrivacyPolicy_Disable_Description {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Disable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deshabilitar el almacenamiento local.
        /// </summary>
        public static string PrivacyPolicy_Disable_Title {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Disable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El almacenamiento local (localStorage) es una característica de HTML5 que permite a los sitios web almacenar datos en el navegador del usuario. A diferencia de las cookies, los datos almacenados en localStorage no tienen una fecha de caducidad y se mantienen en el navegador hasta que se eliminan manualmente..
        /// </summary>
        public static string PrivacyPolicy_LocalStorage_Description {
            get {
                return ResourceManager.GetString("PrivacyPolicy_LocalStorage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Qué es el almacenamiento local (localStorage)?.
        /// </summary>
        public static string PrivacyPolicy_LocalStorage_Title {
            get {
                return ResourceManager.GetString("PrivacyPolicy_LocalStorage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PrivacyPolicy_MoreInfo {
            get {
                return ResourceManager.GetString("PrivacyPolicy_MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derecho a acceder a los datos personales que almacenamos sobre ti..
        /// </summary>
        public static string PrivacyPolicy_Rights_Access {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Rights_Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derecho a solicitar la corrección de datos personales incorrectos o incompletos..
        /// </summary>
        public static string PrivacyPolicy_Rights_Correction {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Rights_Correction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derecho a solicitar la eliminación de tus datos personales..
        /// </summary>
        public static string PrivacyPolicy_Rights_Deletion {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Rights_Deletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependiendo de tu ubicación, puedes tener ciertos derechos con respecto a tus datos personales, incluyendo:.
        /// </summary>
        public static string PrivacyPolicy_Rights_Description {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Rights_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derecho a oponerte al procesamiento de tus datos personales..
        /// </summary>
        public static string PrivacyPolicy_Rights_Object {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Rights_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tus derechos.
        /// </summary>
        public static string PrivacyPolicy_Rights_Title {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Rights_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Política de Privacidad.
        /// </summary>
        public static string PrivacyPolicy_Title {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizamos el almacenamiento local para almacenar información que mejora la experiencia del usuario en nuestro sitio web. La información que almacenamos incluye:.
        /// </summary>
        public static string PrivacyPolicy_Usage_Description {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Usage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tatuajes favoritos: Almacenamos los tatuajes que el usuario ha marcado como favoritos para facilitar el acceso en futuras visitas..
        /// </summary>
        public static string PrivacyPolicy_Usage_Favorites {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Usage_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vista inicial: Almacenamos si el usuario ha visto la vista inicial para no mostrarla nuevamente..
        /// </summary>
        public static string PrivacyPolicy_Usage_InitialView {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Usage_InitialView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma seleccionado: Almacenamos el idioma preferido por el usuario para mostrar el contenido en ese idioma en futuras visitas..
        /// </summary>
        public static string PrivacyPolicy_Usage_Language {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Usage_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Cómo utilizamos el almacenamiento local?.
        /// </summary>
        public static string PrivacyPolicy_Usage_Title {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Usage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requerido.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los derechos reservados.
        /// </summary>
        public static string RightReserved {
            get {
                return ResourceManager.GetString("RightReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENVIAR.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paquetes.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuéntanos menos.
        /// </summary>
        public static string TellUsLess {
            get {
                return ResourceManager.GetString("TellUsLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuéntanos más.
        /// </summary>
        public static string TellUsMore {
            get {
                return ResourceManager.GetString("TellUsMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estudio.
        /// </summary>
        public static string TheArtistTitle {
            get {
                return ResourceManager.GetString("TheArtistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona.
        /// </summary>
        public static string UploadChoose {
            get {
                return ResourceManager.GetString("UploadChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparte con nosotros tu diseño preferido.
        /// </summary>
        public static string UploadDesign {
            get {
                return ResourceManager.GetString("UploadDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VER MAS.
        /// </summary>
        public static string ViewMoreButton {
            get {
                return ResourceManager.GetString("ViewMoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotografía de alta calidad. Nuestro equipo de fotógrafos expertos se dedica a convertir tu visión en realidad con una creatividad inigualable. Estamos comprometidos con la excelencia en cada toma, asegurando una experiencia única y personalizada..
        /// </summary>
        public static string WelcomeDescription {
            get {
                return ResourceManager.GetString("WelcomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu historia en cada imagen, arte en cada detalle..
        /// </summary>
        public static string WelcomeSubtitle {
            get {
                return ResourceManager.GetString("WelcomeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido a CandysoftStudio.
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Con Color.
        /// </summary>
        public static string WithColor {
            get {
                return ResourceManager.GetString("WithColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu Correo Electrónico.
        /// </summary>
        public static string YourEmail {
            get {
                return ResourceManager.GetString("YourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu Nombre.
        /// </summary>
        public static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu Teléfono.
        /// </summary>
        public static string YourPhone {
            get {
                return ResourceManager.GetString("YourPhone", resourceCulture);
            }
        }
    }
}
