//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tattoo.InkVibesTattoo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tattoo.InkVibesTattoo.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to receive promotional messages sent via an autodialer and this agreement isn&apos;t a condition of any purchase..
        /// </summary>
        public static string AcceptConditions {
            get {
                return ResourceManager.GetString("AcceptConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDRESS.
        /// </summary>
        public static string AddressLabel {
            get {
                return ResourceManager.GetString("AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are a passionate and talented team, dedicated to the visual arts and creating unique experiences for our clients. With a strong background in various artistic disciplines, we blend creativity, technique, and a personalized approach to transform every idea into a work of art. From the initial sketches to the final execution, we work closely with our clients to ensure that each project reflects their individuality and style. Our commitment is to deliver high-quality, meaningful work that exceeds expectatio [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AdrianBio {
            get {
                return ResourceManager.GetString("AdrianBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANDYSOFT Studio.
        /// </summary>
        public static string AdrianName {
            get {
                return ResourceManager.GetString("AdrianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studio.
        /// </summary>
        public static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black / White.
        /// </summary>
        public static string BlackAndWhite {
            get {
                return ResourceManager.GetString("BlackAndWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOK NOW.
        /// </summary>
        public static string BookNow {
            get {
                return ResourceManager.GetString("BookNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOK NOW.
        /// </summary>
        public static string BookNowButton {
            get {
                return ResourceManager.GetString("BookNowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At our photography studio, attention to detail is our top priority. We take meticulous care to create a clean, organized, and welcoming environment for our clients. Your comfort and satisfaction are paramount to us, and our commitment to a professional and pristine studio reflects our dedication to providing the best photography experience possible..
        /// </summary>
        public static string CommitmentDescription {
            get {
                return ResourceManager.GetString("CommitmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Commitment to Quality.
        /// </summary>
        public static string CommitmentTitle {
            get {
                return ResourceManager.GetString("CommitmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string ContactUsTitle {
            get {
                return ResourceManager.GetString("ContactUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string CookieConsent_Accept {
            get {
                return ResourceManager.GetString("CookieConsent_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This website uses local storage to ensure you get the best experience..
        /// </summary>
        public static string CookieConsent_Message {
            get {
                return ResourceManager.GetString("CookieConsent_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diverse Styles.
        /// </summary>
        public static string DiverseStyles {
            get {
                return ResourceManager.GetString("DiverseStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date most be greatest than start date.
        /// </summary>
        public static string EndDateInvalid {
            get {
                return ResourceManager.GetString("EndDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string FAQTitle {
            get {
                return ResourceManager.GetString("FAQTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find us.
        /// </summary>
        public static string FindUsButton {
            get {
                return ResourceManager.GetString("FindUsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paquetes.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Directions.
        /// </summary>
        public static string GetDirections {
            get {
                return ResourceManager.GetString("GetDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently Asked Questions.
        /// </summary>
        public static string HeaderFAQ {
            get {
                return ResourceManager.GetString("HeaderFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s START!.
        /// </summary>
        public static string InitViewButton {
            get {
                return ResourceManager.GetString("InitViewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu historia en cada imagen, arte en cada detalle..
        /// </summary>
        public static string InitViewTitle {
            get {
                return ResourceManager.GetString("InitViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Dates.
        /// </summary>
        public static string InvalidDates {
            get {
                return ResourceManager.GetString("InvalidDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this a CoverUp.
        /// </summary>
        public static string IsCoverUp {
            get {
                return ResourceManager.GetString("IsCoverUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can upload a maximum of.
        /// </summary>
        public static string MaximunFiles {
            get {
                return ResourceManager.GetString("MaximunFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destacados.
        /// </summary>
        public static string MyWorkTitle {
            get {
                return ResourceManager.GetString("MyWorkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Limit.
        /// </summary>
        public static string OnLimit {
            get {
                return ResourceManager.GetString("OnLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday - Sunday: 10am - 7pm.
        /// </summary>
        public static string OpeningHours {
            get {
                return ResourceManager.GetString("OpeningHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPENING HOURS.
        /// </summary>
        public static string OpeningHoursLabel {
            get {
                return ResourceManager.GetString("OpeningHoursLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationSuccess.
        /// </summary>
        public static string OperationSuccess {
            get {
                return ResourceManager.GetString("OperationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All ink used at InkVibes Tattoo is of the highest industry standards, 100% vegan-friendly, and non-toxic..
        /// </summary>
        public static string OurInkDescription {
            get {
                return ResourceManager.GetString("OurInkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Ink.
        /// </summary>
        public static string OurInkTitle {
            get {
                return ResourceManager.GetString("OurInkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tattoo needles used at InkVibes Tattoo are of the highest industry standards, pre-sterilized, and single-use..
        /// </summary>
        public static string OurNeedlesDescription {
            get {
                return ResourceManager.GetString("OurNeedlesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Needles.
        /// </summary>
        public static string OurNeedlesTitle {
            get {
                return ResourceManager.GetString("OurNeedlesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We adhere to the highest health and hygiene standards, assuring your safety and ours. All procedures are performed with single-use equipment..
        /// </summary>
        public static string OurProcessDescription {
            get {
                return ResourceManager.GetString("OurProcessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Process.
        /// </summary>
        public static string OurProcessTitle {
            get {
                return ResourceManager.GetString("OurProcessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All equipment and work areas used to perform procedures at InkVibes Tattoo are thoroughly sterilized and cleaned between clients, assuring you peace of mind..
        /// </summary>
        public static string OurSafetyDescription {
            get {
                return ResourceManager.GetString("OurSafetyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Safety.
        /// </summary>
        public static string OurSafetyTitle {
            get {
                return ResourceManager.GetString("OurSafetyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am over the age of 18.
        /// </summary>
        public static string OverAge {
            get {
                return ResourceManager.GetString("OverAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By continuing, you accept our cookies policy..
        /// </summary>
        public static string PolicyNote {
            get {
                return ResourceManager.GetString("PolicyNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string PreferredDate {
            get {
                return ResourceManager.GetString("PreferredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string PreferredTime {
            get {
                return ResourceManager.GetString("PreferredTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudflare may collect information about the requests made to our website, including IP addresses, HTTP headers, and performance data. This information is used to improve the performance and security of the service. Cloudflare does not store personal data for tracking or marketing purposes..
        /// </summary>
        public static string PrivacyPolicy_Cloudflare_Data_Description {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Cloudflare_Data_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What data does Cloudflare collect?.
        /// </summary>
        public static string PrivacyPolicy_Cloudflare_Data_Title {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Cloudflare_Data_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use Cloudflare CDN (Content Delivery Network) to improve the performance and security of our website. Cloudflare caches a copy of our site in multiple locations around the world, allowing users to access content more quickly from the server closest to them. Additionally, Cloudflare offers protection against DDoS attacks and other security threats..
        /// </summary>
        public static string PrivacyPolicy_Cloudflare_Description {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Cloudflare_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of Cloudflare CDN.
        /// </summary>
        public static string PrivacyPolicy_Cloudflare_Title {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Cloudflare_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PrivacyPolicy_Contact {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This privacy policy explains what data we collect and how we use it. You should read this policy to understand what kind of data we store on your device and how that information is used..
        /// </summary>
        public static string PrivacyPolicy_Description {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can disable local storage by adjusting the settings in your browser (consult your browser&apos;s Help to learn how to do this). Note that disabling local storage will affect the functionality of this and many other websites you visit. Disabling local storage will generally result in also disabling certain functionalities and features of this site. Therefore, it is recommended not to disable local storage..
        /// </summary>
        public static string PrivacyPolicy_Disable_Description {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Disable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable local storage.
        /// </summary>
        public static string PrivacyPolicy_Disable_Title {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Disable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local storage (localStorage) is an HTML5 feature that allows websites to store data in the user&apos;s browser. Unlike cookies, data stored in localStorage does not have an expiration date and remains in the browser until it is manually deleted..
        /// </summary>
        public static string PrivacyPolicy_LocalStorage_Description {
            get {
                return ResourceManager.GetString("PrivacyPolicy_LocalStorage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is local storage (localStorage)?.
        /// </summary>
        public static string PrivacyPolicy_LocalStorage_Title {
            get {
                return ResourceManager.GetString("PrivacyPolicy_LocalStorage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PrivacyPolicy_MoreInfo {
            get {
                return ResourceManager.GetString("PrivacyPolicy_MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right to access the personal data we store about you..
        /// </summary>
        public static string PrivacyPolicy_Rights_Access {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Rights_Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right to request correction of inaccurate or incomplete personal data..
        /// </summary>
        public static string PrivacyPolicy_Rights_Correction {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Rights_Correction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right to request deletion of your personal data..
        /// </summary>
        public static string PrivacyPolicy_Rights_Deletion {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Rights_Deletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depending on your location, you may have certain rights regarding your personal data, including:.
        /// </summary>
        public static string PrivacyPolicy_Rights_Description {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Rights_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right to object to the processing of your personal data..
        /// </summary>
        public static string PrivacyPolicy_Rights_Object {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Rights_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your rights.
        /// </summary>
        public static string PrivacyPolicy_Rights_Title {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Rights_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy_Title {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use local storage to store information that improves the user&apos;s experience on our website. The information we store includes:.
        /// </summary>
        public static string PrivacyPolicy_Usage_Description {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Usage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite tattoos: We store the tattoos that the user has marked as favorites to facilitate access on future visits..
        /// </summary>
        public static string PrivacyPolicy_Usage_Favorites {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Usage_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial view: We store whether the user has seen the initial view to avoid showing it again..
        /// </summary>
        public static string PrivacyPolicy_Usage_InitialView {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Usage_InitialView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected language: We store the user&apos;s preferred language to display content in that language on future visits..
        /// </summary>
        public static string PrivacyPolicy_Usage_Language {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Usage_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do we use local storage?.
        /// </summary>
        public static string PrivacyPolicy_Usage_Title {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Usage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved.
        /// </summary>
        public static string RightReserved {
            get {
                return ResourceManager.GetString("RightReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEND.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paquetes.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell Us Less.
        /// </summary>
        public static string TellUsLess {
            get {
                return ResourceManager.GetString("TellUsLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell Us More.
        /// </summary>
        public static string TellUsMore {
            get {
                return ResourceManager.GetString("TellUsMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studio.
        /// </summary>
        public static string TheArtistTitle {
            get {
                return ResourceManager.GetString("TheArtistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string UploadChoose {
            get {
                return ResourceManager.GetString("UploadChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share with us your prefered design.
        /// </summary>
        public static string UploadDesign {
            get {
                return ResourceManager.GetString("UploadDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW MORE.
        /// </summary>
        public static string ViewMoreButton {
            get {
                return ResourceManager.GetString("ViewMoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Candysoft Studio, your premier destination for high-quality photography. Our team of expert photographers is dedicated to turning your vision into reality with unmatched creativity. We are committed to excellence in every shot, ensuring a unique and personalized experience. Discover the difference at Candysoft Studio, where art meets precision in a first-class environment..
        /// </summary>
        public static string WelcomeDescription {
            get {
                return ResourceManager.GetString("WelcomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu historia en cada imagen, arte en cada detalle..
        /// </summary>
        public static string WelcomeSubtitle {
            get {
                return ResourceManager.GetString("WelcomeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Candysoft Studio.
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Color.
        /// </summary>
        public static string WithColor {
            get {
                return ResourceManager.GetString("WithColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email.
        /// </summary>
        public static string YourEmail {
            get {
                return ResourceManager.GetString("YourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Phone.
        /// </summary>
        public static string YourPhone {
            get {
                return ResourceManager.GetString("YourPhone", resourceCulture);
            }
        }
    }
}
